plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle'
}

version = rootProject.version

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir("runs/${name}")
        }

        register('client') {
            args "--mixin.config=${mod_id}.mixins.json"
            if (System.getProperty('os.name').toLowerCase().contains('mac')) {
                jvmArgs '-XstartOnFirstThread'
            }
        }

        register('server') {
            args '--nogui'
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'

    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes 'MixinConfigs': "${mod_id}.mixins.json"
    }
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}
