name: build forge
on:
  pull_request:
    branches: [ "**" ]
    paths:
      - .github/workflows/build-forge.yml
      - build.gradle.kts
      - 'gradle.properties'
      - 'gradle/**'
      - 'buildSrc/**'
      - 'common/**'
      - 'forge/**'
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/build-forge.yml
      - build.gradle.kts
      - 'gradle.properties'
      - 'gradle/**'
      - 'buildSrc/**'
      - 'common/**'
      - 'forge/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: ktlint check
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
          build-root-directory: forge
          arguments: ktlintCheck --no-daemon
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
          build-root-directory: forge
          # --no-daemon required otherwise build fails. The issue is forge-related. It may be fixed later on.
          arguments: build --no-daemon
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: forge/build/libs/
